### ISSUE TITLE
Devices not created in HA

### ISSUE THREAD

**Issue by Schafy** [danielrheinbay/fhemMAX2HASS#3]
Hi Daniel,

I need a litte input here. Checking the MQTT integration in HA, I receive topics from FHEM for "homeassistent/#", but no devices are created. Any ìdea how to debug this? Discovery from zigbee2mqtt using the same mosquitto instance is working fine.

**Comment by Schafy** [comment]
without knowing, what I am doing, I found this video (https://www.youtube.com/watch?v=n9QXRcFqbLY) explaining the new mqtt discovery method introduced in 2024.11. Could this be the issue?

**Comment by danielrheinbay** [comment]
While Home Assistant 2024.11 has indeed introduced a way to discover a device including all of its components, the previous way of discovering components individually still exists:
https://www.home-assistant.io/integrations/mqtt/#device-discovery-payload
https://www.home-assistant.io/integrations/mqtt/#single-component-discovery-payload

> I receive topics from FHEM for "homeassistent/#",
Is that a typo in your post or in your config? It should read homeassist**a**nt instead of homeassist**e**nt

Do you see config messages when you subscribe to
- homeassistant/climate/#
- homeassistant/sensor/#
- homeassistant/binary_sensor/#

Look for messages e.g. in homeassistant/climate/<name of your entity in FHEM>/<MAX id in FHEM>-climate/config

You may want to try a visual tool for debugging purposes, e.g. [MQTT Explorer](http://mqtt-explorer.com/).

Is there anything relevant in your FHEM log files or in your home-assistant.log?

**Comment by Schafy** [comment]
MQTT Explorer confirms messages in

homeassistant/binary_sensory/<device>/<entity>/config
homeassistant/sensory/<device>/<entity>/config
homeassistant/climate/<device>/<entity>/config

and even in MQTT integration I successfully received topics
`Nachricht 6 empfangen auf homeassistant/binary_sensor/MAX_Thermostat_Bad/0c8176-panel/config um 13:31:
{
    "availability": [
        {
            "payload_available": "online",
            "payload_not_available": "offline",
            "topic": "fhem2mqtt/binary_sensor/fhem/availability"
        },
        {
            "payload_available": "alive",
            "payload_not_available": "dead",
            "topic": "fhem2mqtt/MAX_Thermostat_Bad/Activity"
        }
    ],
    "availability_mode": "all",
    "device": {
        "configuration_url": "http://fhem.fritz.box:8083/fhem?detail=MAX_Thermostat_Bad",
        "identifiers": [
            "0c8176"
        ],
        "manufacturer": "MAX",
        "model": "HeatingThermostat",
        "name": "MAX_Thermostat_Bad",
        "suggested_area": "MAX",
        "sw_version": null
    },
    "device_class": "lock",
    "entity_category": "diagnostic",
    "object_id": "MAX-HeatingThermostat-0c8176-panel",
    "payload_off": "locked",
    "payload_on": "unlocked",
    "state_topic": "fhem2mqtt/MAX_Thermostat_Bad/panel",
    "unique_id": "MAX-HeatingThermostat-0c8176-panel"
}`

**Comment by Schafy** [comment]
I found an error message in the mqtt integrations log of HA

ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'string value is None for dictionary value @ data['device']['sw_version']' when processing MQTT discovery message topic: 'homeassistant/binary_sensor/MAX_Thermostat_Kind1/0c8172-battery/config', message: '{'availability': [{'payload_available': 'online', 'payload_not_available': 'offline', 'topic': 'homeassistant/binary_sensor/fhem/availability'}, {'payload_available': 'alive', 'payload_not_available': 'dead', 'topic': 'homeassistant/MAX_Thermostat_Kind1/Activity'}], 'availability_mode': 'all', 'device': {'configuration_url': 'http://fhem.fritz.box:8083/fhem?detail=MAX_Thermostat_Kind1', 'identifiers': ['0c8172'], 'manufacturer': 'MAX', 'model': 'HeatingThermostat', 'suggested_area': 'MAX', 'sw_version': None, 'name': 'MAX_Thermostat_Kind1'}, 'device_class': 'battery', 'entity_category': 'diagnostic', 'object_id': 'MAX-HeatingThermostat-0c8172-battery', 'payload_off': 'ok', 'payload_on': 'low', 'state_topic': 'homeassistant/MAX_Thermostat_Kind1/batteryState', 'unique_id': 'MAX-HeatingThermostat-0c8172-battery'}'

**Comment by Schafy** [comment]
Changeing the firmware default from undef to "1.0" did the trick. My devices in FHEM don't have a "Firmware" reading. Now the devices appear in HA :-)

        # Get the firmware version using ReadingsVal
        my $firmware = ReadingsVal($device, "firmware", "1.0");

**Comment by Schafy** [comment]
Glad I could help. You did all the work. Greetings from Rutesheim ;-)

**Comment by Schafy** [comment]
Little Addition! My cul seems to have lost all pairings and was running in listening mode only. After I repaired all devices, the "firmware" attribute was available to all devices again.

**Comment by danielrheinbay** [comment]
Thank you for following up, @Schafy!
A missing firmware was the root cause of #1, so I'll keep the error handling.
